### ISSUE TITLE
Project: Backpressure Management

### ISSUE THREAD

**Issue by smeubank** [getsentry/team-sdks#10]
## Project Board

See our [project board](https://github.com/orgs/getsentry/projects/128/views/1) to track this initiative across all SDKs

### Problem Statement

In some high throughput situations, specifically, with generation and sending of transaction events, our Backend SDKs may have some negative overhead.

Situationally this can be something like the straw that broke the camels back, meaning the application is already in a bad state, but the SDK should ideally minimize it's impact in the situation.

**As a driver,** the concern is that we lose metrics data from sampling, so we would like to be able to collect as much data as possible from performance data for high fidelity metrics.

example change which caused this issue:
https://github.com/getsentry/sentry/pull/45592/files

### Solution Brainstorm

Internal Vanguard with explanation of imple: [here](https://vanguard.getsentry.net/p/clnlv0iuj0010s60q9e09ba3f)

Develop spec:???

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-docs/issues/7324
- [ ] https://github.com/getsentry/sentry-python/issues/2095
- [ ] https://github.com/getsentry/sentry-php/issues/1563
- [ ] https://github.com/getsentry/sentry-java/issues/2829
- [ ] https://github.com/getsentry/sentry-ruby/issues/2063
- [ ] https://github.com/getsentry/sentry-javascript/issues/8477
- [ ] https://github.com/getsentry/sentry-dotnet/issues/2410
- [ ] Develop Docs
- [ ] Golang
```

**Comment by shanamatthews** [comment]
@sl0thentr0py - qq, is this something that we should document, like on our [performance overhead](https://docs.sentry.io/product/performance/performance-overhead/) page?
