### ISSUE TITLE
Project: GraphQL Support

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/team-sdks#12]
## Project Board

See our [project board](https://github.com/orgs/getsentry/projects/113) to track this initiative across all SDKs

## Measuring Impact

Let's find ways with amplitude to detect how often an issue viewed per platform and sdk, has a graphql error event & importantly is using an SDK which could benefit or in fact does have the benefit
Meaning:
- amplitude event needs to include
  - sdk and version
  - platform
  - error is graphql or not (ideally not boolean let's think more categorical if possible)
  - detect if has the benefits of the new design

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-laravel/pull/720
- [ ] https://github.com/getsentry/sentry-java/issues/2790
- [ ] https://github.com/getsentry/sentry-dotnet/issues/2449
- [ ] https://github.com/getsentry/sentry-python/issues/2198
- [ ] https://github.com/getsentry/sentry-ruby/issues/2091
```
