### ISSUE TITLE
Report as app context what's the current activity during the error

### ISSUE THREAD

**Issue by marandaneto** [getsentry/team-sdks#18]
I'd like to know which Activity/Screen was visible during the error (right now we only know if it's in the background or foreground).
Right now it's only possible by looking at crumbs, I want to make this more visible.
This should be searchable/alertable, I want to know which screens are getting more errors and alert only the screens I care the most.
For transactions this is not needed since the Screen name is already the transaction name.
I want to filter/alert errors that happened during screen X only.

For example, an error that happened after payment is less important than an error during the payment :P

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-java/issues/2664
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3140
- [ ] https://github.com/getsentry/sentry-dart/issues/1411
- [ ] https://github.com/getsentry/sentry-react-native/issues/2994
- [ ] https://github.com/getsentry/relay/pull/2344
```

Other platforms to consider:
- [ ] .NET
- [ ] Unity

**Comment by kahest** [comment]
As discussed for Cocoa here: https://github.com/getsentry/sentry-cocoa/issues/3140#issuecomment-1641992662
- we should consider adding a manual API to set the screen/activity for use cases where automatic detection doesn't work well (e.g. SwiftUI)

**Comment by marandaneto** [comment]
For android: https://github.com/skydoves/snitcher
We can take a look at how on they track "current screen" for crashes.
