### ISSUE TITLE
Project: Update Getting Started docs for enhanced simplicity

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/team-sdks#23]
### Project Board

A progress overview of all SDKs can be found on [our project board](https://github.com/orgs/getsentry/projects/145/views/1).

### Description

We've successfully migrated all the getting-started docs from [sentry-docs](https://sentry.sentry.io/issues/?project=1&query=SENTRY-docs) to the main sentry repository, refer to the initiative https://github.com/getsentry/sentry/issues/48144 for more details. 

Except for the JavaScript SDKs, all other documentation was migrated as-is. However, this necessitated updating the initially created structure for the [Layout](https://github.com/getsentry/sentry/blob/master/static/app/components/onboarding/gettingStartedDoc/layout.tsx) and [Step](https://github.com/getsentry/sentry/blob/master/static/app/components/onboarding/gettingStartedDoc/step.tsx) components to accommodate the diverse range of documentation. As a result, the structure became complex and confusing, contradicting our goal of maintaining simplicity and user-friendliness for non-developers.

The objective of this task is to thoroughly review all documentation, even those not frequently used, and streamline their content under the structured headings of 'Install,' 'Configure,' and 'Verify' and in the optional heading 'Next Steps'. 

If there is critical information essential for new users to get on board, we can include it under the new 'Notes' section. However, the onboarding documentation should strictly focus on the basics to help users get started. All advanced configurations shall be available in the complete documentation displayed on the [sentry-docs website](https://docs.sentry.io/).

_Additionally, please use this opportunity to update code snippets and copies as needed. If a "Verify" step is not yet available, kindly include it in the documentation._

**Note:** A guide was recently added to our "Frontendend Handbook" to help you to add and update getting started docs in sentry's main repository 😉 -> https://develop.sentry.dev/frontend/working-on-getting-started-docs/

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-python/issues/2292
- [ ] https://github.com/getsentry/sentry-react-native/issues/3228
- [ ] https://github.com/getsentry/sentry-dotnet/issues/2532
- [ ] https://github.com/getsentry/sentry-go/issues/688
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3205
- [ ] https://github.com/getsentry/sentry-kotlin-multiplatform/issues/111
- [ ] https://github.com/getsentry/sentry-unity/issues/1415
- [ ] https://github.com/getsentry/sentry-unreal/issues/345
- [ ] https://github.com/getsentry/sentry-rust/issues/602
- [ ] https://github.com/getsentry/sentry-clj/issues/57
- [ ] https://github.com/getsentry/sentry-javascript/issues/8735
- [ ] https://github.com/getsentry/sentry-php/issues/1579
- [ ] https://github.com/getsentry/sentry-java/issues/2884
- [ ] https://github.com/getsentry/sentry-java/issues/2885
- [ ] https://github.com/getsentry/sentry-ruby/issues/2085
- [ ] https://github.com/getsentry/sentry-laravel/issues/760
- [ ] https://github.com/getsentry/sentry-elixir/issues/586
- [ ] https://github.com/getsentry/sentry-capacitor/issues/433
- [ ] https://github.com/getsentry/sentry-dart/issues/1585
- [ ] https://github.com/getsentry/sentry-symfony/issues/752
- [ ] https://github.com/getsentry/sentry-native/issues/869
- [ ] https://github.com/getsentry/sentry-cordova/issues/315
```

### Slack-Channel

#discuss-onboarding

### Notion Document(s)

[[EPIC] Setup Docs Refactor](https://github.com/getsentry/sentry/issues/48144)
[Move Docs to Sentry Repository - RFC](https://github.com/getsentry/rfcs/blob/main/text/0084-move-docs-to-sentry-repository.md)
[Setup Docs Refactor Initiative - Notion Doc](https://www.notion.so/sentry/Setup-docs-refactor-01ed795a111d43569e3ccebe9def4989) (Sorry employees only)

### Stakeholder(s)

@matejminar
@ale-cota 
@smeubank 
@stephanie-anderson 
@kahest 

### Team(s)

Telemetry Experience Team
Mobile Team
Backend SDK Team
Frontend SDK Team

**Comment by cleptric** [comment]
@priscilawebdev can we close this?

**Comment by cleptric** [comment]
Closing this now.
