### ISSUE TITLE
Update CLI sourcemaps explain to debug ID process.

### ISSUE THREAD

**Issue by ale-cota** [getsentry/team-sdks#26]
We need to update the `sentry-cli sourcemaps explain` command to work with debug IDs.

This work depends on: https://github.com/getsentry/sentry/issues/55664

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-cli/issues/1718
- [ ] https://github.com/getsentry/sentry-cli/issues/1601
- [ ] https://github.com/getsentry/sentry-cli/issues/1594
```

**Comment by lforst** [comment]
Discussed this with the team. Since we're going to have the source map debugger modal the long-term solution here will be to deprecate the `sentry-cli sourcemaps explain` command since they're likely equally powerful and we don't want to maintain 2 things.

**Comment by lforst** [comment]
We deprecated and discontinued explain.
