### ISSUE TITLE
Project: Starfish Module: Browser Interactions

### ISSUE THREAD

**Issue by edwardgou-sentry** [getsentry/team-sdks#32]
### Description

Post pageload interactions are a major part of assessing a webpage's performance for real users, especially in highly interactive webapps. Browser sdks currently have an experimental feature for recording interaction transactions via the `enableInteractions` flag. This issue includes requests for further extension of the Javascript SDK interactions experiment to enable building a v0 Browser Interactions focused product/module in Sentry. 

Here are the asks we've scoped for v0:
- [ ] mouse left click down should start an interaction transaction, unless immediately followed up with a mouse left click up. This interaction should have it's own **queryable** unique `transaction.op`, for example `ui.action.left.click.down`
- [ ] mouse right click up should start an interaction transaction. This interaction should have it's own **queryable** unique `transaction.op`, for example `ui.action.right.click.up`
- [ ] mouse right click down should start an interaction transaction, unless immediately followed up with a mouse right click up. This interaction should have it's own **queryable** unique `transaction.op`, for example `ui.action.right.click.down`
- [ ] form submissions should start an interaction transaction, regardless of whether a form submission is occurs due to a mouse button click, or the user presses enter, or any other way. This interaction should have it's own **queryable** unique `transaction.op`, for example `ui.action.form.submitted`
- [ ] If an interaction occurs with a valid target, the `aria-label` of the target should be stored and **queryable** on the interaction transaction **context**
- [ ] If an interaction occurs with a valid target, the target html selector should be stored and **queryable** on the interaction transaction **context**. It is currently being stored as a span description on the interaction span in the experiment.
- [ ] Additionally, SDKs should allow users to configure whether an individual ui interaction type is captured or not, (example: opt in to capture left click ups but dont capture right click ups)

### Slack-Channel

#discuss-starfish

### Notion Document(s)

https://www.notion.so/sentry/Browser-Known-Needed-Data-2f72a8779bf847758b823914c3329c59

### Stakeholder(s)

https://github.com/orgs/getsentry/teams/team-starfish
@alexjillard

### Team(s)

Web Frontend

```[tasklist]
### Tasks
- [ ] Click spans to be created with correct op and name
- [ ] Attribute labels attached to interaction (aria-label required and anything else)
- [ ] Form interaction transactions
- [ ] Come up with test scenarios on self hosted HIWAs
- [ ] Promote experiment into an option. Opt in and opt out options
```

**Comment by edwardgou-sentry** [comment]
If we can get the `aria-label` and target html selector stored in the transaction context, the starfish team can own the discover changes to make them queryable.

**Comment by edwardgou-sentry** [comment]
Closing. No longer relevant since we've moved away from this and we have other similar instrumentation such as inp.
