### ISSUE TITLE
[Chore] Deprecate and remove user.segment

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/team-sdks#44]
### Description

As per https://github.com/getsentry/sentry/issues/58767#issuecomment-1808116241, user segment is deprecated from the user interface and the SDK.

Let's work to remove support for this across the SDKs.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-javascript/pull/10210
- [ ] https://github.com/getsentry/sentry-php/pull/1681
- [ ] https://github.com/getsentry/sentry-python/issues/2718
- [ ] https://github.com/getsentry/sentry-go/pull/928
- [ ] https://github.com/getsentry/sentry-java/issues/3497
- [ ] https://github.com/getsentry/sentry-cocoa/issues/4090
- [ ] https://github.com/getsentry/sentry-cocoa/issues/4093
- [ ] https://github.com/getsentry/sentry-dart/issues/2115
- [x] React Native
- [ ] https://github.com/getsentry/sentry-dotnet/issues/3840
- [ ] https://github.com/getsentry/sentry-ruby/issues/2585
```

### Stakeholder(s)

@AbhiPrasad

### Team(s)

Mobile, Web Backend, Web Frontend

**Comment by krystofwoldrich** [comment]
For RN, it was deprecated when deprecated in JS and will be removed in RN V6 (includes JS V8).

**Comment by AbhiPrasad** [comment]
The deprecation of user segment has happening in all applicable SDKs. SDKs now are responsible for removing it in future. Closing this issue for now.
