### ISSUE TITLE
Document data collected by SDKs

### ISSUE THREAD

**Issue by antonpirker** [getsentry/team-sdks#82]
### Description

On https://docs.sentry.io there must be a page "Data Management" > "Data Collected" for each SDK. This page lists the data that is collected by the SDK. 

A pilot page is already existing in the Python SDK: https://docs.sentry.io/platforms/python/data-management/data-collected/ (this page can be copied and update to match the data collected in the respective SDK)

### Why should we be doing this?

- This is important for showing users that we care about privacy. 
- It helps our customers to be GDPR compliant (because they need to document what data they collect from their users) 
- This documentation also helps solution and sales engineers in their work with big clients. 

### Why now?

Every couple of weeks someone asks for this. 

(This was decided on in an [RFC](https://github.com/getsentry/rfcs/blob/main/text/0070-document-sensitive-data-collected.md) long time ago. Although the scope of the RFC was greatly reduced to make it feasible)

### Notion Document(s)

Related DACI: https://www.notion.so/sentry/DACI-user-ip_address-auto-behind-sendDefaultPii-true-1818b10e4b5d802f8938e894fd0348d5

### Stakeholder(s)

@HazAT 

### Team(s)

Mobile, Backend, Frontend, GDX

### SDKs

```[tasklist]
## SDKs
- [x] Python SDK https://docs.sentry.io/platforms/python/data-management/data-collected/
- [x] PHP SDK https://docs.sentry.io/platforms/php/data-management/data-collected/
- [x] Symfony SDK https://docs.sentry.io/platforms/php/guides/symfony/data-management/data-collected/
- [x] Laravel SDK https://docs.sentry.io/platforms/php/guides/laravel/data-management/data-collected/
- [x] Ruby SDK https://github.com/getsentry/sentry-docs/pull/12669
- [x] Android SDK https://github.com/getsentry/sentry-java/issues/4092
- [x] Apple/Cocoa SDK https://github.com/getsentry/sentry-docs/issues/12751
- [x] Dart/Flutter SDK https://github.com/getsentry/sentry-dart/issues/2692
- [x] React Native SDK https://github.com/getsentry/sentry-react-native/issues/4539
- [x] Java SDK https://github.com/getsentry/sentry-java/issues/4092
- [ ] JavaScript SDK
- [ ] Electron SDK
- [ ] Go SDK
- [ ] Elixir SDK
- [ ] Rust SDK
- [ ] .NET SDK
- [ ] Unity SDK
- [ ] Unreal SDK
- [ ] PowerShell SDK
- [ ] Native SDK
- [ ] Capacitor SDK
- [ ] Cordova SDK
- [ ] Kotlin Multiplatform SDK
- [ ] Sentry CLI
```
